import {useEffect,useState,type FormEvent} from 'react';
import {Link,Navigate,useSearchParams} from 'react-router-dom';
import {z} from 'zod';
import {useApi} from '../api';
import {sessionSchema} from '../auth';
import {familyRequest} from '../family';
import {familiesSchema,childrenSchema,membersSchema,grantsSchema,devicesSchema,setupSchema,draftSchema,type Family,type Grant} from '../../../shared/family';
import {AuthLayout,FormNotice} from '../components/AuthLayout';
import {Loading,ErrorState} from '../components/Common';
import {Icon} from '../components/Icon';
function useFamilyAction(){const [busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');return {busy,error,message,setMessage,async run(fn:()=>Promise<void>){if(busy)return;setBusy(true);setError('');setMessage('');try{await fn();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}};}
function FamilyNav(){return <nav className="family-nav" aria-label="가족과 계정"><Link to="/family" aria-current="page"><Icon name="home"/>우리 가족</Link><Link to="/device/connect"><Icon name="device"/>아이 기기 연결</Link><Link to="/account"><Icon name="settings"/>내 계정</Link></nav>;}
export function FamilyPage(){
 const session=useApi('/api/account/session',sessionSchema);
 if(session.loading)return <AuthLayout wide><Loading label="가족 연결을 확인하고 있어요"/></AuthLayout>;
 if(session.error)return <AuthLayout wide><ErrorState message={session.error} retry={session.retry}/></AuthLayout>;
 if(!session.data?.authenticated)return <Navigate to="/login" replace/>;
 if(session.data.assurance==='LOW')return <Navigate to="/account" replace/>;
 return <AuthLayout wide><FamilyNav/><div className="family-heading"><div><span className="eyebrow">함께하는 사람들</span><h1>우리 가족을 연결해요</h1><p>아이마다 함께할 보호자와 공유할 정보를 정해요.</p></div><span className="account-symbol"><Icon name="home"/></span></div><FamilySetup/></AuthLayout>;
}
function FamilySetup(){
 const setup=useApi('/api/v1/setup',setupSchema);
 if(setup.loading)return <Loading label="연결 상태를 확인하고 있어요"/>;
 if(setup.error)return <ErrorState message={setup.error} retry={setup.retry}/>;
 if(!setup.data?.accountReady||!setup.data.databaseReady)return <section className="family-welcome"><span className="feature-symbol"><Icon name="shield"/></span><span className="badge amber">서비스 연결 준비 중</span><h2>아이 정보는 확인을 마친 뒤에</h2><p>로그인 후 보호자 확인을 거쳐 가족을 연결해요.<br/>지금은 실제 아이 정보를 등록할 수 없어요.</p><ol className="family-steps"><li><span>1</span><div><strong>보호자 확인</strong><small>본인과 아이의 관계를 확인해요.</small></div></li><li><span>2</span><div><strong>공유 범위 선택</strong><small>위치 공유는 따로 선택할 수 있어요.</small></div></li><li><span>3</span><div><strong>아이 기기 연결</strong><small>아이 기기에 뜬 번호를 보호자가 확인해요.</small></div></li></ol><button className="button primary full" disabled>보호자 확인 · 준비 중</button><Link className="auth-back" to="/account">내 계정 확인 <Icon name="arrow"/></Link></section>;
 return <FamilyWorkspace/>;
}
function FamilyWorkspace(){
 const families=useApi('/api/v1/me',familiesSchema),action=useFamilyAction();const [search,setSearch]=useSearchParams();const selected=families.data?.families.find(f=>f.id===search.get('family'))||families.data?.families[0];
 async function create(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget;const name=String(new FormData(form).get('name'));await action.run(async()=>{const result=await familyRequest<{id:string}>('/api/v1/families',{name});form.reset();setSearch({family:result.id});families.retry();});}
 return <><FormNotice error={action.error} message={action.message}/>{families.loading?<Loading label="우리 가족을 불러오고 있어요"/>:families.error?<ErrorState message={families.error} retry={families.retry}/>:<>
 {families.data!.families.length>0&&<div className="family-selector"><label htmlFor="family-choice">함께하는 가족</label><select id="family-choice" value={selected?.id} onChange={e=>setSearch({family:e.target.value})}>{families.data!.families.map(f=><option value={f.id} key={f.id}>{f.name}</option>)}</select></div>}
 {!selected?<section className="family-welcome"><span className="feature-symbol"><Icon name="home"/></span><h2>함께할 가족을 만들어 보세요</h2><p>가족을 만든 뒤 보호자를 초대할 수 있어요.<br/>초대에 참여했다면 운영자의 승인을 기다려 주세요.</p><form onSubmit={create} className="auth-form"><div className="form-field"><label htmlFor="family-name">가족 이름</label><input id="family-name" name="name" required maxLength={40} placeholder="예: 우리 가족"/></div><button className="button primary full" disabled={action.busy}>우리 가족 만들기 <Icon name="plus"/></button></form><button className="button full" onClick={families.retry}>참여 상태 새로고침</button></section>:<FamilyDetail key={selected.id} family={selected} refresh={families.retry}/>}
 </>}</>;
}
function FamilyDetail({family,refresh}:{family:Family;refresh:()=>void}){
 const children=useApi(`/api/v1/families/${family.id}/children`,childrenSchema),members=useApi(`/api/v1/families/${family.id}/members`,membersSchema),action=useFamilyAction();
 const [invite,setInvite]=useState(''),[draft,setDraft]=useState<string|null>(null),[child,setChild]=useState<string|null>(null),[ownerTarget,setOwnerTarget]=useState('');
 const selected=children.data?.children.find(c=>c.id===child);
 function reload(){children.retry();members.retry();refresh();}
 return <><FormNotice error={action.error} message={action.message}/><div className="family-grid"><section className="account-card family-children"><div className="card-title"><h2><Icon name="sun"/>함께 챙기는 아이</h2><span className="badge green">승인된 아이만 표시</span></div><p>가족 운영권과 아이 정보 공유 권한은 별도로 관리해요.</p>
 {children.loading?<Loading label="아이 목록을 확인하고 있어요"/>:children.error?<ErrorState message={children.error} retry={children.retry}/>:children.data?.children.length?<div className="child-cards">{children.data.children.map(c=><button className={`child-summary ${child===c.id?'selected':''}`} key={c.id} onClick={()=>setChild(c.id)} aria-pressed={child===c.id}><span className="child-avatar"><Icon name="sun"/></span><span><strong>{c.nickname}</strong><small>{c.canManage?'동의·공유·기기 관리':'공유받은 아이'}</small></span><Icon name="chevron"/></button>)}</div>:<div className="family-empty"><Icon name="sun"/><strong>아직 공유받은 아이가 없어요</strong><p>등록 동의를 마치거나 아이의 보호자에게 공유 승인을 요청해 주세요.</p></div>}
 <button className="button primary full" disabled={action.busy} onClick={()=>action.run(async()=>{const d=await familyRequest<{id:string}>(`/api/v1/families/${family.id}/child-registration-drafts`,{});setDraft(d.id);})}><Icon name="plus"/>아이 등록 시작</button><p className="account-caption">별명과 생년월일은 관계 확인 후에 입력해요.</p>
 </section><section className="account-card"><div className="card-title"><h2><Icon name="home"/>함께하는 보호자</h2><span className="badge neutral">최대 5명</span></div>
 {members.loading?<Loading label="함께하는 보호자를 불러오고 있어요"/>:members.error?<ErrorState message={members.error} retry={members.retry}/>:members.data?.members.map(m=><div className="family-member" key={m.id}><div><strong>{m.name}</strong><small>{m.owner?'가족 운영자':m.status==='PENDING'?'참여 승인 대기':'함께하는 보호자'}</small></div>{family.owner&&m.status==='PENDING'?<button className="button compact" disabled={action.busy} onClick={()=>action.run(async()=>{await familyRequest(`/api/v1/memberships/${m.id}/approve`,{expectedVersion:m.version});members.retry();action.setMessage('함께하는 가족이 되었어요. 아이 정보 공유는 따로 승인해 주세요.');})}>참여 승인</button>:family.owner&&!m.owner?<button className="button compact" disabled={action.busy} onClick={()=>{if(window.confirm('가족 참여와 공유받은 아이 정보 접근을 해제할까요?'))void action.run(async()=>{await familyRequest(`/api/v1/memberships/${m.id}/revoke`,{expectedVersion:m.version});reload();});}}>참여 해제</button>:null}</div>)}
 {family.owner&&<><button className="button full" disabled={action.busy} onClick={()=>action.run(async()=>{const r=await familyRequest<{inviteUrl:string}>(`/api/v1/families/${family.id}/invites`,{});setInvite(r.inviteUrl);})}><Icon name="plus"/>보호자 초대</button>{invite&&<div className="invite-box"><label htmlFor="invite-link">24시간 동안 사용할 초대 링크</label><input id="invite-link" readOnly value={invite} onFocus={e=>e.currentTarget.select()}/><button className="button full" onClick={()=>action.run(async()=>{await navigator.clipboard.writeText(invite);action.setMessage('초대 링크를 복사했어요. 함께할 보호자에게 보내 주세요.');})}>링크 복사</button><small>새 링크를 만들면 이전의 미사용 링크는 만료돼요.</small></div>}
 <details className="family-advanced"><summary>가족 운영권 이전</summary><p>초대와 참여 승인을 맡을 보호자를 바꿔요. 아이 공유 권한은 그대로예요.</p><label htmlFor="next-owner">새 운영자</label><select id="next-owner" value={ownerTarget} onChange={e=>setOwnerTarget(e.target.value)}><option value="">보호자를 선택해 주세요</option>{members.data?.members.filter(m=>!m.owner&&m.status==='ACTIVE').map(m=><option key={m.id} value={m.memberId}>{m.name}</option>)}</select><button className="button full" disabled={!ownerTarget||action.busy} onClick={()=>{if(window.confirm('선택한 보호자에게 가족 운영권을 이전할까요?'))void action.run(async()=>{await familyRequest(`/api/v1/families/${family.id}/owner`,{memberId:ownerTarget,expectedVersion:family.version});reload();});}}>운영권 이전</button></details></>}
 </section></div>
 {draft&&<ChildRegistration key={draft} familyId={family.id} draftId={draft} close={()=>setDraft(null)} done={()=>{setDraft(null);children.retry();}}/>}
 {selected&&(selected.canManage?<ChildManagement key={selected.id} child={selected} refresh={children.retry}/>:<section className="account-card"><h2>{selected.nickname}</h2><p>공유받은 정보는 일정과 대화 메뉴에서 확인할 수 있어요. 해당 메뉴는 다음 단계에서 연결합니다.</p></section>)}
 </>;
}
function ChildRegistration({familyId,draftId,close,done}:{familyId:string;draftId:string;close:()=>void;done:()=>void}){
 const draft=useApi(`/api/v1/child-registration-drafts/${draftId}`,draftSchema),action=useFamilyAction();
 async function activate(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=new FormData(e.currentTarget);await action.run(async()=>{const proof=await familyRequest<{proofId:string}>(`/api/v1/child-registration-drafts/${draftId}/consent-proofs`,{general:form.get('general')==='on',location:form.get('location')==='on',policyVersion:'6.1'});await familyRequest(`/api/v1/families/${familyId}/children`,{draftId,proofId:proof.proofId,nickname:form.get('nickname'),birthDate:draft.data?.birthDate});done();});}
 return <section className="account-card registration-panel"><div className="card-title"><h2><Icon name="shield"/>아이 등록</h2><button className="icon-button" aria-label="아이 등록 닫기" onClick={close}><Icon name="close"/></button></div><FormNotice error={action.error}/>
 {draft.loading?<Loading label="등록 상태를 확인하고 있어요"/>:draft.error?<ErrorState message={draft.error} retry={draft.retry}/>:draft.data?.state==='VERIFIED'?<form className="auth-form" onSubmit={activate}><fieldset disabled={action.busy}><legend>공유 범위 선택</legend><div className="form-field"><label htmlFor="child-nickname">아이 별명</label><input name="nickname" id="child-nickname" maxLength={24} required/></div><p>확인된 생년월일 {draft.data.birthDate}</p><label className="check-option"><input name="general" type="checkbox" required/><span>일정·대화·학원비를 위한 아이 정보 처리에 동의해요. (필수, 정책 6.1)</span></label><label className="check-option"><input name="location" type="checkbox"/><span>아이가 직접 보내는 위치 공유에 동의해요. (선택)</span></label><p className="account-caption">위치 공유를 선택하지 않아도 일정과 대화를 사용할 수 있어요. 동의는 아이 관리에서 철회할 수 있어요.</p><button className="button primary full">동의하고 아이 등록</button></fieldset></form>:<><span className="badge amber">보호자 관계 확인 필요</span><h3>아이와의 관계를 먼저 확인해요</h3><p>확인 서비스가 아직 연결되지 않았어요. 실제 아이의 이름이나 생년월일을 입력하지 마세요.</p><button className="button full" disabled={action.busy} onClick={()=>action.run(async()=>{await familyRequest(`/api/v1/child-registration-drafts/${draftId}/verification-sessions`,{});draft.retry();})}>관계 확인 상태 확인</button><button className="button full" onClick={draft.retry}>등록 상태 새로고침</button><small>진행하지 않은 등록은 24시간 뒤 만료돼요.</small></>}
 </section>;
}
function GrantEditor({grant,childId,locationConsent,refresh}:{grant:Grant;childId:string;locationConsent:boolean;refresh:()=>void}){
 const [value,setValue]=useState(grant),action=useFamilyAction();const fields=[['daily','일정과 등하원'],['chat','가족 대화'],['location','아이 위치'],['tuitionRead','학원비 보기'],['tuitionWrite','학원비 기록']] as const;
 return <form className="grant-editor" onSubmit={e=>{e.preventDefault();void action.run(async()=>{await familyRequest(`/api/v1/children/${childId}/grants/${grant.memberId}`,{daily:value.daily,chat:value.chat,location:value.location,tuitionRead:value.tuitionRead,tuitionWrite:value.tuitionWrite,expectedVersion:grant.version},'PUT');refresh();});}}><h4>{grant.name}{grant.consenter&&<span className="badge green">동의권자</span>}</h4><fieldset disabled={grant.consenter||action.busy}><legend className="sr-only">{grant.name} 공유 범위</legend><div className="grant-options">{fields.map(([key,label])=><label className="check-option" key={key}><input type="checkbox" checked={value[key]} disabled={key==='location'&&!locationConsent} onChange={e=>{const checked=e.target.checked;setValue(v=>({...v,[key]:checked,...(key==='tuitionWrite'&&checked?{tuitionRead:true}:{}),...(key==='tuitionRead'&&!checked?{tuitionWrite:false}:{})}));}}/><span>{label}</span></label>)}</div>{!grant.consenter&&<button className="button full">공유 범위 저장</button>}</fieldset><FormNotice error={action.error}/></form>;
}
function ChildManagement({child,refresh}:{child:z.infer<typeof childrenSchema>['children'][number];refresh:()=>void}){
 const grants=useApi(`/api/v1/children/${child.id}/grants`,grantsSchema),devices=useApi(`/api/v1/children/${child.id}/devices`,devicesSchema),action=useFamilyAction();
 const [code,setCode]=useState(''),[resolved,setResolved]=useState<{id:string;label:string;version:number}|null>(null);
 return <section className="account-card child-management"><div className="card-title"><h2>{child.nickname} · 공유와 기기</h2><span className="badge green">동의권자 관리</span></div><FormNotice error={action.error} message={action.message}/><div className="family-grid"><div><h3><Icon name="shield"/>보호자별 공유 범위</h3><p>체크한 정보만 해당 보호자에게 보여요.</p>{grants.loading?<Loading label="공유 범위를 확인하고 있어요"/>:grants.error?<ErrorState message={grants.error} retry={grants.retry}/>:grants.data?.grants.map(g=><GrantEditor key={`${g.memberId}-${g.version}`} grant={g} childId={child.id} locationConsent={child.locationConsent} refresh={grants.retry}/>)}</div><div><h3><Icon name="device"/>아이 기기 연결</h3><p>아이 기기에서 아이하루의 <strong>아이 기기 연결</strong>을 열고, 화면의 번호를 여기에 입력해 주세요.</p><form className="auth-form" onSubmit={e=>{e.preventDefault();void action.run(async()=>{const r=await familyRequest<{id:string;label:string;version:number}>('/api/v1/device-pairings/resolve',{code});setResolved(r);});}}><div className="form-field"><label htmlFor="pair-code">6자리 연결 번호</label><input id="pair-code" inputMode="numeric" autoComplete="off" pattern="[0-9]{6}" maxLength={6} value={code} onChange={e=>{setCode(e.target.value.replace(/\D/g,''));setResolved(null);}} required/></div><button className="button full" disabled={action.busy||code.length!==6}>연결할 기기 확인</button></form>{resolved&&<div className="pair-approval"><strong>{resolved.label}</strong><p>이 기기를 {child.nickname}의 기기로 연결할까요?</p><button className="button primary full" disabled={action.busy} onClick={()=>action.run(async()=>{await familyRequest(`/api/v1/device-pairings/${resolved.id}/approve`,{childId:child.id,expectedVersion:resolved.version});setResolved(null);setCode('');action.setMessage('승인했어요. 아이 기기에서 연결 확인을 눌러 주세요.');})}>이 아이의 기기로 승인</button></div>}
 <h4>연결된 기기 · 최대 2대</h4>{devices.loading?<Loading label="기기를 확인하고 있어요"/>:devices.error?<ErrorState message={devices.error} retry={devices.retry}/>:devices.data?.devices.length?devices.data.devices.map(d=><div className="family-member" key={d.id}><div><strong>{d.label}</strong><small>최근 사용 {new Date(d.lastSeenAt).toLocaleDateString('ko-KR')}</small></div><button className="button compact" disabled={action.busy} onClick={()=>{if(window.confirm('이 아이 기기의 연결을 해제할까요?'))void action.run(async()=>{await familyRequest(`/api/v1/children/${child.id}/devices/${d.id}`,{},'DELETE');devices.retry();});}}>해제</button></div>):<p className="account-caption">아직 연결된 아이 기기가 없어요.</p>}<button className="button full" onClick={devices.retry}>연결 목록 새로고침</button>
 </div></div><details className="family-advanced"><summary>동의와 데이터 관리</summary><p>위치 동의를 철회해도 일정과 대화는 사용할 수 있어요. 일반 정보 동의를 철회하면 아이 기기의 접근이 차단되고 데이터 삭제가 접수돼요.</p>{child.locationConsent&&<button className="button" disabled={action.busy} onClick={()=>{if(window.confirm('아이의 위치 공유 동의를 철회할까요?'))void action.run(async()=>{await familyRequest(`/api/v1/children/${child.id}/consents/revoke`,{purpose:'location',expectedVersion:child.version});refresh();grants.retry();});}}>위치 공유 동의 철회</button>}<button className="button danger-text" disabled={action.busy} onClick={()=>{if(window.confirm('일반 정보 동의를 철회하고 아이 정보 삭제를 접수할까요?'))void action.run(async()=>{await familyRequest(`/api/v1/children/${child.id}/consents/revoke`,{purpose:'general',expectedVersion:child.version});refresh();});}}>일반 동의 철회 · 삭제 접수</button></details></section>;
}
export function FamilyInvitePage(){
 const [token]=useState(()=>window.location.hash.slice(1)),action=useFamilyAction(),session=useApi('/api/account/session',sessionSchema);
 useEffect(()=>{window.history.replaceState(null,'','/family/invite');},[]);
 return <AuthLayout><div className="auth-title"><span className="eyebrow">가족 초대</span><h2>함께하는 하루의 시작</h2><p>참여를 신청하면 가족 운영자가 확인해요.<br/>아이 정보는 별도의 공유 승인 후 볼 수 있어요.</p></div><FormNotice error={action.error} message={action.message}/>{session.loading?<Loading label="계정을 확인하고 있어요"/>:!session.data?.authenticated?<><Link className="button primary full" to="/login">로그인하기</Link><p className="auth-help">로그인한 뒤 받은 초대 링크를 다시 열어 주세요.</p></>:!token?<p>사용할 초대 링크를 다시 열어 주세요.</p>:<button className="button primary full" disabled={action.busy||!!action.message} onClick={()=>action.run(async()=>{await familyRequest('/api/v1/invites/accept',{token});action.setMessage('참여를 신청했어요. 가족 운영자의 승인을 기다려 주세요.');})}>가족 참여 신청</button>}<Link className="auth-back" to="/family">우리 가족으로 <Icon name="arrow"/></Link></AuthLayout>;
}
