import {useEffect,useRef,useState,type ReactNode} from 'react';
import {scheduleInput,changeInput,previewResponse,occurrenceSchema,addDays,type Occurrence,type ChangePreview,type ChangeInput,type ScheduleSeries} from '../../../shared/schedules';
import {z} from 'zod';
import {scheduleRequest,useScheduleAction} from '../schedules';
import {FormNotice} from './AuthLayout';
import {Icon} from './Icon';
export const weekLabels=['일','월','화','수','목','금','토'];
function Dialog({title,busy,close,children}:{title:string;busy:boolean;close:()=>void;children:ReactNode}){
 const ref=useRef<HTMLDialogElement>(null);
 useEffect(()=>{ref.current?.showModal();},[]);
 return <dialog ref={ref} className="schedule-dialog" aria-labelledby="schedule-dialog-title" onCancel={e=>{if(busy)e.preventDefault();}} onClose={close}>
  <div className="schedule-dialog-heading"><h2 id="schedule-dialog-title">{title}</h2><button className="icon-button" disabled={busy} aria-label="일정 편집 닫기" onClick={()=>ref.current?.close()}><Icon name="close"/></button></div>{children}
 </dialog>;
}
function Weekdays({value,change}:{value:number[];change:(v:number[])=>void}){return <fieldset className="schedule-weekdays"><legend>반복 요일</legend>{weekLabels.map((label,i)=><label key={label} className={value.includes(i)?'selected':''}><input type="checkbox" checked={value.includes(i)} onChange={()=>change(value.includes(i)?value.filter(d=>d!==i):[...value,i].sort())}/><span>{label}</span></label>)}</fieldset>;}
function HolidayField({value,change}:{value:'KEEP'|'SKIP'|'ASK';change:(v:'KEEP'|'SKIP'|'ASK')=>void}){return <label className="form-field">공휴일에는<select value={value} onChange={e=>change(e.target.value as typeof value)}><option value="ASK">진행 여부 확인하기 · 기본</option><option value="KEEP">정상 진행</option><option value="SKIP">휴강</option></select><small>공휴일 정보를 받지 못한 날짜는 정책과 관계없이 확인이 필요해요.</small></label>;}
export function NewScheduleDialog({childrenOptions,childId,date,today,makeup,close,saved}:{childrenOptions:{id:string;nickname:string}[];childId:string;date:string;today:string;makeup?:Occurrence;close:()=>void;saved:()=>void}){
 const action=useScheduleAction();const [child,setChild]=useState(makeup?.childId||childId||childrenOptions[0]?.id||'');
 const [form,setForm]=useState({title:makeup?`${makeup.title} 보강`:'',place:makeup?.place||'',date,untilDate:addDays(date,90),startTime:makeup?.startTime||'15:00',endTime:makeup?.endTime||'16:00',frequency:makeup?'ONCE' as const:'WEEKLY' as 'ONCE'|'WEEKLY',weekdays:[1,3,5],holidayPolicy:'ASK' as 'KEEP'|'SKIP'|'ASK'});
 function field<K extends keyof typeof form>(key:K,value:(typeof form)[K]){setForm(v=>({...v,[key]:value}));}
 return <Dialog title={makeup?'보강 일정 등록':'새 일정 등록'} busy={action.busy} close={close}><form className="auth-form" onSubmit={e=>{e.preventDefault();void action.run(async keyFor=>{
  const parsed=scheduleInput.safeParse({...form,untilDate:form.frequency==='ONCE'?form.date:form.untilDate,...(makeup?{makeupForOccurrenceId:makeup.id}:{})});
  if(!parsed.success)throw new Error('제목·요일·시작과 종료 시각을 확인해 주세요.');
  const result=await scheduleRequest<{overlaps:number}>(`/api/v1/children/${child}/schedules`,parsed.data,'POST',keyFor({child,...parsed.data}));
  if(result.overlaps>0)window.alert('등록했어요. 시간이 겹치는 일정이 있으니 달력에서 확인해 주세요.');saved();
 });}}><FormNotice error={action.error}/>{makeup&&<p className="auth-notice">원래 일정의 취소·휴강 기록은 유지돼요. 보강은 별도 일정으로 등록해요.</p>}
 <fieldset disabled={action.busy} className="schedule-fields"><legend className="sr-only">일정 정보</legend>
 <label className="form-field">아이<select value={child} disabled={!!makeup} onChange={e=>setChild(e.target.value)} required>{childrenOptions.map(c=><option key={c.id} value={c.id}>{c.nickname}</option>)}</select></label>
 <label className="form-field">일정 이름<input autoFocus value={form.title} onChange={e=>field('title',e.target.value)} required maxLength={80} placeholder="예: 영어 학원"/></label>
 <label className="form-field">장소<input value={form.place} onChange={e=>field('place',e.target.value)} maxLength={120} placeholder="예: 해봄 영어교실"/></label>
 <div className="schedule-form-row"><label className="form-field">시작 날짜<input type="date" value={form.date} min={today} max={addDays(today,365)} onChange={e=>field('date',e.target.value)} required/></label><label className="form-field">반복<select value={form.frequency} disabled={!!makeup} onChange={e=>field('frequency',e.target.value as 'ONCE'|'WEEKLY')}><option value="ONCE">한 번만</option><option value="WEEKLY">매주 반복</option></select></label></div>
 <div className="schedule-form-row"><label className="form-field">시작 시각<input type="time" value={form.startTime} onChange={e=>field('startTime',e.target.value)} required/></label><label className="form-field">종료 시각<input type="time" value={form.endTime} onChange={e=>field('endTime',e.target.value)} required/></label></div>
 {form.frequency==='WEEKLY'&&<><Weekdays value={form.weekdays} change={v=>field('weekdays',v)}/><label className="form-field">반복 종료 날짜<input type="date" value={form.untilDate} min={form.date} max={addDays(form.date,365)} onChange={e=>field('untilDate',e.target.value)} required/><small>최대 1년까지 등록하고, 앞으로 56일의 회차를 확인할 수 있어요.</small></label></>}
 <HolidayField value={form.holidayPolicy} change={v=>field('holidayPolicy',v)}/></fieldset>
 <button className="button primary full" disabled={action.busy||!child}>{action.busy?'저장 중…':'일정 등록'}</button></form></Dialog>;
}
export function EditScheduleDialog({item,close,saved}:{item:Occurrence;close:()=>void;saved:()=>void}){
 const action=useScheduleAction();const [current,setCurrent]=useState(item),[scope,setScope]=useState<'ONE'|'FUTURE'>('ONE');
 const [effective,setEffective]=useState(item.anchorDate),[title,setTitle]=useState(item.title),[place,setPlace]=useState(item.place),[start,setStart]=useState(item.startTime),[end,setEnd]=useState(item.endTime),[date,setDate]=useState(item.date),[days,setDays]=useState<number[]>([]),[changeDays,setChangeDays]=useState(false),[cancel,setCancel]=useState(false),[reason,setReason]=useState(''),[later,setLater]=useState<'KEEP'|'REPLACE'|''>(''),[preview,setPreview]=useState<{result:ChangePreview;input:ChangeInput}|null>(null);
 const [policy,setPolicy]=useState<'KEEP'|'SKIP'|'ASK'|''>(''),[until,setUntil]=useState('');
 function invalidate(){setPreview(null);action.clear();}
 return <Dialog title="일정 변경" busy={action.busy} close={close}><form className="auth-form" onChange={invalidate} onSubmit={e=>{e.preventDefault();void action.run(async()=>{
  const changes:Record<string,unknown>={title,place,startTime:start,endTime:end};
  if(scope==='ONE'){changes.date=date;changes.cancelled=cancel;if(cancel)changes.reason=reason;}
  else {if(changeDays)changes.weekdays=days;if(policy)changes.holidayPolicy=policy;if(until)changes.untilDate=until;}
  const input=changeInput.safeParse({scope,changes,effectiveDate:scope==='ONE'?current.anchorDate:effective,expectedVersion:current.resourceVersion,...(later?{laterVersions:later}:{})});
  if(!input.success)throw new Error('반복 요일과 변경 내용을 확인해 주세요.');
  const result=previewResponse.parse(await scheduleRequest(`/api/v1/occurrences/${current.id}/change-preview`,input.data));setPreview({result,input:input.data});
 });}}><p className="account-caption">{item.childName} · {item.anchorDate} 기준 회차</p><FormNotice error={action.error}/>
 {action.code==='VERSION_CONFLICT'&&<button type="button" className="button full" onClick={()=>action.run(async()=>{const r=z.object({occurrence:occurrenceSchema}).parse(await scheduleRequest(`/api/v1/occurrences/${current.id}`));setCurrent(r.occurrence);setPreview(null);})}>입력 유지하고 최신 버전 불러오기</button>}
 <fieldset disabled={action.busy} className="schedule-fields"><legend className="sr-only">변경 내용</legend>
 <label className="form-field">변경 범위<select value={scope} onChange={e=>{setScope(e.target.value as typeof scope);setCancel(false);}}><option value="ONE">이번 일정만</option><option value="FUTURE">이번 및 이후</option></select></label>
 {scope==='FUTURE'?<><label className="form-field">변경 적용 날짜<input type="date" value={effective} min={current.anchorDate} onChange={e=>setEffective(e.target.value)} required/></label><p className="account-caption">개별 변경과 지난 기록은 유지돼요. 단건 일정은 ‘이번 일정만’을 선택하세요.</p></>:<label className="form-field">일정 날짜<input type="date" value={date} onChange={e=>setDate(e.target.value)} required/></label>}
 <label className="form-field">일정 이름<input value={title} onChange={e=>setTitle(e.target.value)} maxLength={80} required/></label><label className="form-field">장소<input value={place} onChange={e=>setPlace(e.target.value)} maxLength={120}/></label>
 <div className="schedule-form-row"><label className="form-field">시작 시각<input type="time" value={start} onChange={e=>setStart(e.target.value)} required/></label><label className="form-field">종료 시각<input type="time" value={end} onChange={e=>setEnd(e.target.value)} required/></label></div>
 {scope==='ONE'?<><label className="check-option"><input type="checkbox" checked={cancel} onChange={e=>setCancel(e.target.checked)}/>이번 일정 취소</label>{cancel&&<label className="form-field">취소 사유<input value={reason} onChange={e=>setReason(e.target.value)} maxLength={160} required/></label>}</>:<><label className="check-option"><input type="checkbox" checked={changeDays} onChange={e=>setChangeDays(e.target.checked)}/>반복 요일도 변경</label>{changeDays&&<Weekdays value={days} change={setDays}/>}<label className="form-field">공휴일 진행 기준<select value={policy} onChange={e=>setPolicy(e.target.value as typeof policy)}><option value="">기존 기준 유지</option><option value="ASK">진행 여부 확인하기</option><option value="KEEP">정상 진행</option><option value="SKIP">휴강</option></select></label><label className="form-field">반복 종료 날짜 변경 · 선택<input type="date" value={until} min={effective} onChange={e=>setUntil(e.target.value)}/><small>비워 두면 기존 종료일을 유지해요. 이미 예약한 미래 변경을 유지하면 그 시작일 전까지만 적용돼요.</small></label><label className="form-field">이미 예약한 미래 변경<select value={later} onChange={e=>setLater(e.target.value as typeof later)}><option value="">미리보기에서 확인 후 선택</option><option value="KEEP">기존 미래 변경 유지</option><option value="REPLACE">지금 내용으로 미래 변경 대체</option></select></label></>}
 </fieldset><button className="button full" disabled={action.busy}>변경 미리보기</button></form>
 {preview&&<section className="change-preview" aria-live="polite"><h3>변경 전 확인해 주세요</h3><dl><div><dt>조회 범위 내 영향 회차</dt><dd>{preview.result.affected}개</dd></div><div><dt>유지되는 개별 변경</dt><dd>{preview.result.preservedExceptions}개</dd></div><div><dt>보존되는 지난·연결 기록</dt><dd>{preview.result.protectedOccurrences}개</dd></div><div><dt>예약된 미래 변경</dt><dd>{preview.result.laterVersions}개</dd></div></dl>{preview.result.overlaps>0&&<p className="auth-notice">다른 일정과 시간이 겹치는 회차가 {preview.result.overlaps}개 있어요.</p>}{preview.result.requiresLaterChoice&&<p className="auth-notice">미래 변경을 유지할지 대체할지 선택한 뒤 다시 미리보기를 눌러 주세요.</p>}<p className="account-caption">미리보기는 5분간 유효해요. 데이터 변경 시 다시 확인해요.</p><button className="button primary full" disabled={action.busy||preview.result.requiresLaterChoice} onClick={()=>action.run(async keyFor=>{const body={...preview.input,previewToken:preview.result.previewToken};await scheduleRequest(`/api/v1/occurrences/${current.id}`,body,'PATCH',keyFor(body));saved();})}>{action.busy?'적용 중…':'확인한 내용 적용'}</button></section>}
 </Dialog>;
}
export function ClosureDialog({series,today,close,saved}:{series:ScheduleSeries;today:string;close:()=>void;saved:()=>void}){
 const action=useScheduleAction();const [from,setFrom]=useState(today>series.fromDate?today:series.fromDate),[to,setTo]=useState(today>series.fromDate?today:series.fromDate),[kind,setKind]=useState('BREAK'),[reason,setReason]=useState('');
 return <Dialog title="기관 휴강·방학" busy={action.busy} close={close}><p>{series.childName} · {series.versions.at(-1)?.title}</p><p className="account-caption">국가 공휴일과 별도로 이 일정의 기관 휴무 기간을 기록해요. 보호자가 개별 확인한 회차는 유지돼요.</p><form className="auth-form" onSubmit={e=>{e.preventDefault();void action.run(async keyFor=>{const body={from,to,kind,reason,expectedVersion:series.resourceVersion};await scheduleRequest(`/api/v1/schedule-series/${series.id}/closures`,body,'POST',keyFor(body));saved();});}}><FormNotice error={action.error}/><div className="schedule-form-row"><label className="form-field">휴무 시작<input type="date" value={from} min={today>series.fromDate?today:series.fromDate} max={series.untilDate} onChange={e=>setFrom(e.target.value)} required/></label><label className="form-field">휴무 종료<input type="date" value={to} min={from} max={series.untilDate} onChange={e=>setTo(e.target.value)} required/></label></div><label className="form-field">구분<select value={kind} onChange={e=>setKind(e.target.value)}><option value="BREAK">휴강</option><option value="VACATION">방학</option></select></label><label className="form-field">안내 내용<input value={reason} onChange={e=>setReason(e.target.value)} placeholder="예: 학원 여름방학" maxLength={80} required/></label><button className="button primary full" disabled={action.busy}>휴무 기간 저장</button></form></Dialog>;
}
